name: siskamling
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0' # Sebaiknya gunakan rentang versi

dependencies:
  flutter:
    sdk: flutter
    
  mobile_scanner: ^5.1.1 
  geolocator: ^12.0.0
  geolocator_android: 4.6.1
  http: ^1.2.1
  camera: ^0.10.5+9
  path_provider: ^2.1.3
  flutter_image_compress: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_local_notifications: ^17.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # 1. Package dipindahkan ke sini
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# 2. Blok konfigurasi dipindahkan ke luar 'flutter:'
# Pastikan 'flutter_launcher_icons:' ini tidak memiliki spasi di depannya.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_siskamling.png"
  min_sdk_android: 21